name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.10']
        os: [ubuntu-latest]
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
      # - shell: bash
      #   run: |
      #     sudo apt-get install csh
      #     wget https://github.com/sqlp/sedumi/releases/download/v1.3.8/sedumi.tgz
      #     tar -xf sedumi.tgz
      #     ls -l
      # - uses: matlab-actions/run-command@v2
      #   with:
      #     command: cd("sedumi"), install_sedumi
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      # - uses: julia-actions/cache@v2
      - name: Set MATLAB environment variables
        run: |
          echo "MATLAB_ROOT=/opt/hostedtoolcache/MATLAB/2024.1.999/x64" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$MATLAB_ROOT/bin/glnxa64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      - shell: julia --color=yes {0}
        run: |
          const libeng = Ref{Ptr{Cvoid}}()
          const eng_open = Ref{Ptr{Cvoid}}()
          libeng_path = joinpath(ENV["MATLAB_ROOT"], "bin", "glnxa64", "libeng")
          libeng[] = Libdl.dlopen(libeng_path, Libdl.RTLD_GLOBAL)
          eng_open[] = Libdl.dlsym(libeng[], :engOpen)
          ep = ccall(
            eng_open[], 
            Ptr{Cvoid}, 
            (Ptr{UInt8},),
            "-nodisplay -nosplash -nodesktop",
          )
          @show ep
      # - uses: julia-actions/julia-buildpkg@v1
      # - uses: julia-actions/julia-runtest@v1
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v4
      #   with:
      #     file: lcov.info
      #     token: ${{ secrets.CODECOV_TOKEN }}
